# Project information
site_name: P4H - Material
site_description: Material para cursos de programação e análise de dados
site_author: P4H
site_url: https://p4husp.github.io/material-2021/

# Repository
repo_name: p4husp/material-2021
repo_url: https://github.com/p4hUSP/material-2021
# Copyright
copyright: Copyright &copy; 2021 Programação para Humanidades

# Configuration
theme:
  name: material
  language: pt
  palette:
    primary: white
    accent: red
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/p4husp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/p4husp
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/p4husp
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/p4husp

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight