---
title: "Material"
author: "P4H"
output: md_document
---

# Material

## Quem somos?

A P4H é um grupo formado por alunos de ciências sociais com o objetivo de aproximar alunos e profissionais da área de tecnologia, programação e análise de dados.

## Como estudar?

Programação __não__ se aprende apenas lendo livros e assistindo aulas. É fundamental que você dedique pelo menos 1 hora do seu dia para estudar. Além disso, recomendamos que você evite apenas copiar e colar o código do site para o seu computador. Escrever as funções é ótimo para memorizá-las e entender os parâmetros que as fazem funcionar.

## O que é uma linguagem de programação e por que utilizamos uma para análise de dados?

Uma das maiores diferenças não diz respeito ao lado técnico. Analisar dados em Python ou em R é grátis! Isso mesmo, você não precisa gastar um centavo para ter acesso a bibliotecas de análise de dados desenvolvidas pelo Google, Amazon, Projeto Apache, entre outras tantas.

Além disso, ao contrário do Excel, do Stata e do SPSS, o R lhe dá liberdade para resolver problemas mediante __algorítmos__. Ou seja, se você é capaz de descrever um passo-a-passo, uma receita, de como obter um resultado a partir de determinadas entradas, podemos escrever um programa e deixar que o computador faça o resto.