name: Deploy Page

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.4'
      - name: Install Ubuntu Dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev
      - name: Install R Dependencies
        run: |
          install.packages(c("remotes", "tidyverse", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Install Mkdocs Dependencies
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - name: Check
        run: |
          chmod +x _deploy.sh
          ./_deploy.sh
